sudo: required
services:
  - docker

before_install:
  - docker build -t dominic70/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dominic70/react-test npm test -- --coverage
  # - docker run -e CI=true dominic70/react-test npm test

after_success:
  - docker build -t dominic70/multi-client ./client
  - docker build -t dominic70/multi-nginx ./nginx
  - docker build -t dominic70/multi-server ./server
  - docker build -t dominic70/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Tahe the images and push to Docker hub
  - docker push dominic70/multi-client
  - docker push dominic70/multi-nginx
  - docker push dominic70/multi-server
  - docker push dominic70/multi-worker 

# http://multidocker-env-1.eba-e4bq76rs.eu-west-2.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-eu-west-2-661394686668
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRETE_KEY
